# Generated by Django 5.1.1 on 2024-10-06 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('imagen', models.ImageField(upload_to='documentos/')),
                ('procesado', models.BooleanField(default=False)),
                ('datos_extraidos', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Documento',
            },
        ),
    ]
